### ISSUE TITLE
Should explain that the repo matches an insecure initial build

### ISSUE THREAD

**Issue by alex-gadea** [snyk-labs/nodejs-docker-best-practices#1]
and that users should follow the docs at https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ to turn the insecure build in this repo into a secure build as described in the article.

The way the readme reads now makes it appear that THIS repo is the secure build and someone may naively copy over the files.

A better thing to do would be to setup a base directory, with step 1, step 2, etc. directories with one directory specified as the final directory and it should be very clear THAT is the secure version.

**Comment by pascalandy** [comment]
you should also link back to the post: https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/

**Comment by lirantal** [comment]
Thanks folks, I've made the update to the README to make it clear
